"""The routing half of the compatibility contracts: what the evaluator owes.

The configuration rewrite must leave a project with no configuration routed
exactly as the release before it. This module turns one evaluator result
into the fields that promise covers, so the capture script and the test
compare the same thing. The capture script writes a baseline once, from the
release the rewrite starts from; the test never writes one, because a
baseline regenerated by the new code would record a regression as expected.
"""
from __future__ import annotations

import copy
import gzip
import hashlib
import itertools
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "cli"))

from compass_pkg.core import CompassError, load_yaml  # noqa: E402
from compass_pkg.routing import evaluate_route  # noqa: E402

FIXTURES = ROOT / "tests" / "fixtures" / "compat"
ROUTING = FIXTURES / "contract-1-routing.jsonl.gz"
OWED = FIXTURES / "contract-2-owed.yml"
POLICY = ROOT / "governance" / "routing-policy.yml"

DIMENSIONS = ("risk", "familiarity", "size", "goal", "urgency", "role")
AUTONOMY = ("controlled", "balanced", "autonomous")


def shipped_policy():
    return load_yaml(str(POLICY))


def compact(readings, policy):
    """The fields the compatibility promise covers, for every autonomy
    setting, or the refusal text when the evaluator refuses."""
    out = {}
    for autonomy in AUTONOMY:
        try:
            r = evaluate_route(copy.deepcopy(readings), policy, autonomy=autonomy)
        except CompassError as exc:
            return {"error": str(exc)}
        if not out:
            out = {
                "delivery_approach": r["delivery_approach"],
                "stages": r["stages"],
                "gates": sorted(r["gates"]),
                "artifacts": sorted((a["kind"], a["depth"]) for a in r["artifacts"]),
                "subtask_ceiling": r["subtask_ceiling"],
                "required_artifacts": sorted(r["required_artifacts"]),
                "required_skills": sorted(r["required_skills"]),
                "blocked_phases": r["blocked_phases"],
                "max_worktrees": r["max_worktrees"],
                "rules_fired": [f["id"] for f in r["policy_rules_fired"]],
                "checkpoints": {},
            }
        out["checkpoints"][autonomy] = r["checkpoints"]
    # Through JSON, so a tuple and a list compare alike after a round trip.
    return json.loads(json.dumps(out, sort_keys=True))


def digest(result):
    text = json.dumps(result, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def grid(vocabulary):
    """Every closed assessment, in a fixed order, with no labels."""
    for values in itertools.product(*(vocabulary[d] for d in DIMENSIONS)):
        readings = dict(zip(DIMENSIONS, values))
        readings["labels"] = []
        yield readings


def label_subsets(labels):
    for n in range(len(labels) + 1):
        for subset in itertools.combinations(labels, n):
            yield list(subset)


def named_labels(policy):
    """Every label a routing predicate names: only these can change a result."""
    found = set()

    def walk(node):
        if isinstance(node, dict):
            for key, value in node.items():
                if key == "labels_any" and isinstance(value, list):
                    found.update(value)
                walk(value)
        elif isinstance(node, list):
            for item in node:
                walk(item)

    walk(policy)
    return sorted(found)


def load_routing():
    """The captured baseline: its header and its rows."""
    with gzip.open(ROUTING, "rt", encoding="utf-8") as fh:
        lines = [json.loads(line) for line in fh if line.strip()]
    return lines[0], lines[1:]


def legacy_spelling(result):
    """A routing result from the layered path, spelled as 5.6.0 spelled it.

    The shipped preset names a required document by its id (`intent`,
    `launch-readiness`) and a blocked stage by its current name (`ship`). The
    5.6.0 policy file named them `intent.md`, `launch-readiness.md` and `land`,
    and the generated view still does. This maps exactly those three names back
    and changes nothing else, so any other name still differs from the baseline
    and a layered result is compared with it field for field."""
    if "error" in result:
        return result
    out = dict(result)
    out["required_artifacts"] = sorted(
        SPELLED_AS_5_6_0_ARTIFACT.get(a, a) for a in result["required_artifacts"])
    out["blocked_phases"] = [
        dict(b, phase=SPELLED_AS_5_6_0_STAGE.get(b["phase"], b["phase"]))
        for b in result["blocked_phases"]]
    return out


SPELLED_AS_5_6_0_ARTIFACT = {"intent": "intent.md",
                             "launch-readiness": "launch-readiness.md"}
SPELLED_AS_5_6_0_STAGE = {"ship": "land"}


def routing_differences(policy, header, rows, first_only=False, layered=False):
    """Every place `policy` routes differently from the baseline, as text.
    Empty when the two agree everywhere the baseline recorded. With
    `first_only`, it stops at the first difference, which is all a test
    that plants a fault needs."""
    found = []
    labels = header["labels"]
    for row in rows:
        if row["kind"] in ("grid", "archive"):
            now = compact(row["assessment"], policy)
            if layered:
                now = legacy_spelling(now)
            if now != row["result"]:
                found.append(f"{row['kind']} {row['assessment']}: "
                             f"{_first_difference(row['result'], now)}")
                if first_only:
                    return found
        elif row["kind"] == "label-digests":
            assessment = row["assessment"]
            for subset, expected in zip(label_subsets(labels), row["digests"]):
                readings = dict(assessment, labels=subset)
                now = compact(readings, policy)
                if digest(legacy_spelling(now) if layered else now) != expected:
                    found.append(f"labels {subset} on {assessment}: result changed")
                    if first_only:
                        return found
    return found


def _first_difference(old, new):
    if "error" in old or "error" in new:
        return f"was {old.get('error', 'routed')!r}, now {new.get('error', 'routed')!r}"
    for key in sorted(set(old) | set(new)):
        if old.get(key) != new.get(key):
            return f"{key} was {old.get(key)!r}, now {new.get(key)!r}"
    return "no difference"


def owed_by_approach(rows):
    """Contract 2: for each delivery approach, every distinct combination of
    gates and artifacts it owes across the label-free grid."""
    owed = {}
    for row in rows:
        result = row.get("result") or {}
        if row["kind"] != "grid" or "error" in result:
            continue
        key = json.dumps({"gates": result["gates"], "artifacts": result["artifacts"]},
                         sort_keys=True)
        owed.setdefault(result["delivery_approach"], set()).add(key)
    return {approach: [json.loads(k) for k in sorted(keys)]
            for approach, keys in sorted(owed.items())}


# --- contracts 3 and 6: verdicts and readability over the archive sample -------

ARCHIVE = FIXTURES / "contract-3-check-verdicts.json"
CLI = ROOT / "cli" / "compass"


def _issues(root):
    work = Path(root) / ".compass" / "work"
    return sorted(p.name for p in work.iterdir() if (p / "manifest.yml").is_file())


def archive_results(root, only=None):
    """For each sampled issue: `compass check`'s exit and its verdict per
    check, and the exit of `issue lint` and `issue receipt`. Contract 3 is
    the verdicts; contract 6 is that old records stay readable."""
    import subprocess

    def run(*args):
        return subprocess.run([sys.executable, str(CLI), *args], cwd=root,
                              capture_output=True, text=True)

    results = {}
    for slug in _issues(root):
        if only and slug not in only:
            continue
        check = run("check", "--issue", slug, "--json")
        try:
            verdicts = {c["name"]: c["status"] for c in json.loads(check.stdout)["checks"]}
        except (ValueError, KeyError, TypeError):
            verdicts = {"unreadable output": check.stdout[-200:]}
        results[slug] = {
            "check_exit": check.returncode,
            "verdicts": verdicts,
            "lint_exit": run("issue", "lint", "--issue", slug).returncode,
            "receipt_exit": run("issue", "receipt", "--issue", slug).returncode,
        }
    return results


def archive_differences(recorded, now):
    found = []
    for slug in sorted(set(recorded) | set(now)):
        old, new = recorded.get(slug), now.get(slug)
        if old != new:
            found.append(f"{slug}: {_first_difference(old or {}, new or {})}")
    return found


# --- configurations B and C ------------------------------------------------------
#
# The contracts hold under three configurations: A (nothing, the shipped
# default alone), B (an empty overlay) and C (a copy of the 5.6.0 governance
# files, read through the legacy adapter). The files for C are byte copies of
# what 5.6.0 shipped, taken once with `git show v5.6.0:governance/<file>`.

# Packed, so the prose scans do not read the 5.6.0 wording as this tree's.
GOVERNANCE_5_6_0 = FIXTURES / "v5.6.0-governance.tgz"
GOVERNANCE_FILES = ("routing-policy.yml", "guardrails.yml")
EMPTY_OVERLAY = "schema: 1\nextends: compass:default@6\n"
# `fault` plants a change in the builder, so a contract run under the
# configuration has something to see:
#   routing: a valid configuration that routes differently from 5.6.0;
#   broken:  a configuration Compass cannot read.
PLANTED_OVERLAY = EMPTY_OVERLAY + (
    "approaches:\n  regular:\n    set:\n      subtask_ceiling: 5\n"
    "      gates: [verify.correctness, verify.governance, verify.traceability,"
    " verify.clarity, verify.security]\n")
BROKEN_OVERLAY = EMPTY_OVERLAY + "approaches: oops\n"


def add_governance_copy(root, fault=None):
    """Put the 5.6.0 governance files in `root/governance/`."""
    folder = Path(root) / "governance"
    folder.mkdir(parents=True, exist_ok=True)
    import tarfile
    with tarfile.open(GOVERNANCE_5_6_0) as tar:
        for name in GOVERNANCE_FILES:
            member = tar.extractfile(f"governance/{name}")
            (folder / name).write_bytes(member.read())
    policy = folder / "routing-policy.yml"
    if fault == "routing":
        import yaml
        data = yaml.safe_load(policy.read_text(encoding="utf-8"))
        shape = data["route_shapes"]["standard"]
        shape["gates"] = [g for g in shape["gates"] if g != "verify.regression"]
        policy.write_text(yaml.safe_dump(data, sort_keys=False), encoding="utf-8")
    elif fault == "broken":
        policy.write_text("version: 1\nroute_shapes: oops\n", encoding="utf-8")
        (folder / "guardrails.yml").write_text("version: 1\ndefaults: oops\n",
                                               encoding="utf-8")


def build_configuration(kind, root, fault=None):
    """Add configuration `kind` to a project root that has a `.compass/`."""
    root = Path(root)
    if kind == "B":
        text = {"routing": PLANTED_OVERLAY, "broken": BROKEN_OVERLAY}.get(
            fault, EMPTY_OVERLAY)
        (root / "compass.yml").write_text(text, encoding="utf-8")
    elif kind == "C":
        add_governance_copy(root, fault)
    elif kind != "A":
        raise ValueError(f"unknown configuration {kind!r}")


def policy_under(kind, scratch, fault=None):
    """The routing policy the evaluator reads for a project in configuration
    `kind`: the resolved configuration, in the shape `evaluate_route` takes."""
    from compass_pkg import effective

    root = Path(scratch) / "project"
    (root / ".compass" / "work").mkdir(parents=True)
    build_configuration(kind, root, fault)
    resolution = effective.resolve_live(str(root))
    view = effective.EffectiveView("live", None, None, resolution.resolved,
                                   resolution.versions)
    return view.evaluator_policy()


def archive_under(kind, fault=None):
    """A copy of the archive sample with configuration `kind` added. It sits
    beside the sample's cache, inside this checkout, because some checks ask
    git about the commits an issue names. The caller removes it."""
    import shutil
    import tempfile

    from archive import CACHE, sample_root

    CACHE.mkdir(exist_ok=True)
    root = Path(tempfile.mkdtemp(dir=CACHE, prefix=f"config-{kind}-"))
    shutil.copytree(sample_root(), root, dirs_exist_ok=True, symlinks=True)
    build_configuration(kind, root, fault)
    return root
