"""The routing half of the compatibility contracts: what the evaluator owes.

The configuration rewrite must leave a project with no configuration routed
exactly as the release before it. This module turns one evaluator result
into the fields that promise covers, so the capture script and the test
compare the same thing. The capture script writes a baseline once, from the
release the rewrite starts from; the test never writes one, because a
baseline regenerated by the new code would record a regression as expected.
"""
from __future__ import annotations

import copy
import gzip
import hashlib
import itertools
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "cli"))

from compass_pkg.core import CompassError, load_yaml  # noqa: E402
from compass_pkg.routing import evaluate_route  # noqa: E402

FIXTURES = ROOT / "tests" / "fixtures" / "compat"
ROUTING = FIXTURES / "contract-1-routing.jsonl.gz"
OWED = FIXTURES / "contract-2-owed.yml"
POLICY = ROOT / "governance" / "routing-policy.yml"

DIMENSIONS = ("risk", "familiarity", "size", "goal", "urgency", "role")
AUTONOMY = ("controlled", "balanced", "autonomous")


def shipped_policy():
    return load_yaml(str(POLICY))


# The baseline was captured at 5.6.0, before the depth words and the size were
# renamed (issue `vocabulary-and-cli-renames`), and is never regenerated. So a
# result is compared in the old words: the size an assessment names is read
# as the new word the evaluator expects, and the stage weights and artifact
# depths it returns are written back as the old words. This table is the one
# place the comparison knows the rename. A verdict that differs after the
# bridge has moved, and the test says which field.
SIZE_NOW = {"standard": "medium"}
DEPTH_WAS = {"thorough": "full", "lightweight": "light",
             "thorough-with-follow-up": "full-plus-backfill"}


def compact(readings, policy):
    """The fields the compatibility promise covers, for every autonomy
    setting, or the refusal text when the evaluator refuses."""
    out = {}
    readings = dict(readings)
    if "size" in readings:
        readings["size"] = SIZE_NOW.get(readings["size"], readings["size"])
    for autonomy in AUTONOMY:
        try:
            r = evaluate_route(copy.deepcopy(readings), policy, autonomy=autonomy)
        except CompassError as exc:
            return {"error": str(exc)}
        if not out:
            out = {
                "delivery_approach": r["delivery_approach"],
                "stages": {s: DEPTH_WAS.get(m, m) for s, m in r["stages"].items()},
                "gates": sorted(r["gates"]),
                "artifacts": sorted((a["kind"], DEPTH_WAS.get(a["depth"], a["depth"]))
                                    for a in r["artifacts"]),
                "subtask_ceiling": r["subtask_ceiling"],
                "required_artifacts": sorted(r["required_artifacts"]),
                "required_skills": sorted(r["required_skills"]),
                "blocked_phases": r["blocked_phases"],
                "max_worktrees": r["max_worktrees"],
                "rules_fired": [f["id"] for f in r["policy_rules_fired"]],
                "checkpoints": {},
            }
        out["checkpoints"][autonomy] = r["checkpoints"]
    # Through JSON, so a tuple and a list compare alike after a round trip.
    return json.loads(json.dumps(out, sort_keys=True))


def digest(result):
    text = json.dumps(result, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def grid(vocabulary):
    """Every closed assessment, in a fixed order, with no labels."""
    for values in itertools.product(*(vocabulary[d] for d in DIMENSIONS)):
        readings = dict(zip(DIMENSIONS, values))
        readings["labels"] = []
        yield readings


def label_subsets(labels):
    for n in range(len(labels) + 1):
        for subset in itertools.combinations(labels, n):
            yield list(subset)


def named_labels(policy):
    """Every label a routing predicate names: only these can change a result."""
    found = set()

    def walk(node):
        if isinstance(node, dict):
            for key, value in node.items():
                if key == "labels_any" and isinstance(value, list):
                    found.update(value)
                walk(value)
        elif isinstance(node, list):
            for item in node:
                walk(item)

    walk(policy)
    return sorted(found)


def load_routing():
    """The captured baseline: its header and its rows."""
    with gzip.open(ROUTING, "rt", encoding="utf-8") as fh:
        lines = [json.loads(line) for line in fh if line.strip()]
    return lines[0], lines[1:]


def routing_differences(policy, header, rows, first_only=False):
    """Every place `policy` routes differently from the baseline, as text.
    Empty when the two agree everywhere the baseline recorded. With
    `first_only`, it stops at the first difference, which is all a test
    that plants a fault needs."""
    found = []
    labels = header["labels"]
    for row in rows:
        if row["kind"] in ("grid", "archive"):
            now = compact(row["assessment"], policy)
            if now != row["result"]:
                found.append(f"{row['kind']} {row['assessment']}: "
                             f"{_first_difference(row['result'], now)}")
                if first_only:
                    return found
        elif row["kind"] == "label-digests":
            assessment = row["assessment"]
            for subset, expected in zip(label_subsets(labels), row["digests"]):
                readings = dict(assessment, labels=subset)
                if digest(compact(readings, policy)) != expected:
                    found.append(f"labels {subset} on {assessment}: result changed")
                    if first_only:
                        return found
    return found


def _first_difference(old, new):
    if "error" in old or "error" in new:
        return f"was {old.get('error', 'routed')!r}, now {new.get('error', 'routed')!r}"
    for key in sorted(set(old) | set(new)):
        if old.get(key) != new.get(key):
            return f"{key} was {old.get(key)!r}, now {new.get(key)!r}"
    return "no difference"


def owed_by_approach(rows):
    """Contract 2: for each delivery approach, every distinct combination of
    gates and artifacts it owes across the label-free grid."""
    owed = {}
    for row in rows:
        result = row.get("result") or {}
        if row["kind"] != "grid" or "error" in result:
            continue
        key = json.dumps({"gates": result["gates"], "artifacts": result["artifacts"]},
                         sort_keys=True)
        owed.setdefault(result["delivery_approach"], set()).add(key)
    return {approach: [json.loads(k) for k in sorted(keys)]
            for approach, keys in sorted(owed.items())}


# --- contracts 3 and 6: verdicts and readability over the archive sample -------

ARCHIVE = FIXTURES / "contract-3-check-verdicts.json"
CLI = ROOT / "cli" / "compass"


def _issues(root):
    work = Path(root) / ".compass" / "work"
    return sorted(p.name for p in work.iterdir() if (p / "manifest.yml").is_file())


def archive_results(root, only=None):
    """For each sampled issue: `compass check`'s exit and its verdict per
    check, and the exit of `issue lint` and `issue receipt`. Contract 3 is
    the verdicts; contract 6 is that old records stay readable."""
    import subprocess

    def run(*args):
        return subprocess.run([sys.executable, str(CLI), *args], cwd=root,
                              capture_output=True, text=True)

    results = {}
    for slug in _issues(root):
        if only and slug not in only:
            continue
        check = run("check", "--issue", slug, "--json")
        try:
            verdicts = {c["name"]: c["status"] for c in json.loads(check.stdout)["checks"]}
        except (ValueError, KeyError, TypeError):
            verdicts = {"unreadable output": check.stdout[-200:]}
        results[slug] = {
            "check_exit": check.returncode,
            "verdicts": verdicts,
            "lint_exit": run("issue", "lint", "--issue", slug).returncode,
            "receipt_exit": run("issue", "receipt", "--issue", slug).returncode,
        }
    return results


def archive_differences(recorded, now):
    found = []
    for slug in sorted(set(recorded) | set(now)):
        old, new = recorded.get(slug), now.get(slug)
        if old != new:
            found.append(f"{slug}: {_first_difference(old or {}, new or {})}")
    return found
