"""The build rule for check implementation versions (ADR-038).

Each built-in check implementation carries a version and a fixture corpus. A
lock file, `tests/fixtures/impls/versions.lock.yml`, holds per implementation
its `version` and a `verdict_digest` of the verdicts its corpus computes. The
build fails when:

- the verdict digest changed and the major version did not (bump the major);
- the installed major is higher than the locked one and the lock file was not
  updated in the same change.

The claim is narrow. Across majors the CLI refuses (`test_impl_refusal.py`).
Within a major, compatibility is shown on the corpus cases only; a change of
behaviour that no case exercises is not detected. The seed corpus is two cases
for each check, built by `tests/check_corpus_runner.py`, so the claim is weak
and grows as cases are added. `docs/check-implementations.md` lists what each
corpus exercises and is derived by `scripts/impl-coverage.py`.

Scenario ids: `IR-6`, `IR-7` and `IR-12` (issue `impl-refusal`). Each test name
starts with its scenario id.
"""
from __future__ import annotations

import dataclasses
import hashlib
import importlib.util
import shutil
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "cli"))
sys.path.insert(0, str(ROOT / "tests"))

from compass_pkg import check_registry  # noqa: E402

import check_corpus_runner as runner  # noqa: E402

CORPUS = ROOT / "tests" / "fixtures" / "impls"
LOCK = CORPUS / "versions.lock.yml"
PAGE = ROOT / "docs" / "check-implementations.md"
SCRIPT = ROOT / "scripts" / "impl-coverage.py"
MARKER = "<!-- generated by `scripts/impl-coverage.py` -->"


def verdict_digest(impl: str, verdicts: dict[str, str]) -> str:
    """Digest of the computed verdicts only, so rewording an `input` line is
    not a change of behaviour, and relabelling a case does not move it."""
    lines = "\n".join(f"{impl}/{name}:{verdict}"
                      for name, verdict in sorted(verdicts.items()))
    return hashlib.sha256(lines.encode("utf-8")).hexdigest()


def current_digests(scratch: Path) -> dict[str, str]:
    return {impl: verdict_digest(impl, runner.computed_verdicts(impl, scratch))
            for impl in check_registry.REGISTRY}


def lock_problems(versions: dict[str, str], digests: dict[str, str],
                  lock: dict[str, dict]) -> list[str]:
    """The build rule, one line per problem, naming the implementation.

    `versions` and `digests` are what the code and corpus say now; `lock` is
    what the last change recorded."""
    problems = []
    for impl, version in sorted(versions.items()):
        locked = lock.get(impl)
        if locked is None:
            problems.append(f"{impl} is not in the lock file")
            continue
        major, locked_major = (int(version.split(".")[0]),
                               int(str(locked["version"]).split(".")[0]))
        if major > locked_major:
            problems.append(
                f"{impl} is at major {major} but the lock file records "
                f"{locked_major}; update the lock file in the same change")
        elif major < locked_major:
            problems.append(
                f"{impl} is at major {major} but the lock file records "
                f"{locked_major}; a major never goes back")
        elif digests[impl] != locked["verdict_digest"]:
            problems.append(
                f"{impl} verdicts changed and its major stayed at {major}; "
                f"bump the major and update the lock file")
    for impl in sorted(set(lock) - set(versions)):
        problems.append(f"{impl} is in the lock file but not in the registry")
    return problems


def _now(scratch):
    versions = {n: e.version for n, e in check_registry.REGISTRY.items()}
    return versions, current_digests(scratch)


def _next_major(versions):
    return f"{int(versions['suite-passed'].split('.')[0]) + 1}.0.0"


def _next_minor(versions):
    major, minor, _ = versions["suite-passed"].split(".")
    return f"{major}.{int(minor) + 1}.0"


def _locked(versions, digests):
    return {n: {"version": versions[n], "verdict_digest": digests[n]} for n in versions}


# --- IR-7: the lock file ---------------------------------------------------------------------

def test_ir_7_the_lock_holds_a_version_and_a_verdict_digest_per_implementation():
    lock = yaml.safe_load(LOCK.read_text(encoding="utf-8"))["implementations"]
    assert set(lock) == set(check_registry.REGISTRY)
    for impl, entry in lock.items():
        assert set(entry) == {"version", "verdict_digest"}, impl


def test_ir_7_the_committed_lock_matches_the_registry_and_computed_verdicts(tmp_path):
    versions, digests = _now(tmp_path)
    lock = yaml.safe_load(LOCK.read_text(encoding="utf-8"))["implementations"]
    assert lock_problems(versions, digests, lock) == []


# --- IR-6: the rule -------------------------------------------------------------------------

def test_ir_6_a_changed_implementation_verdict_fails_and_names_it(tmp_path, monkeypatch):
    versions, digests = _now(tmp_path / "before")
    lock = _locked(versions, digests)
    # The planted change: the implementation now passes whatever it is given,
    # with no label edited and no version bumped.
    entry = check_registry.REGISTRY["suite-passed"]
    monkeypatch.setitem(check_registry.REGISTRY, "suite-passed",
                        dataclasses.replace(entry, fn=lambda task, task_dir: (True, "")))
    problems = lock_problems(versions, current_digests(tmp_path / "after"), lock)
    assert len(problems) == 1 and problems[0].startswith("suite-passed ")
    assert "bump the major" in problems[0]


def test_ir_6_a_higher_major_than_the_lock_fails_until_the_lock_is_updated(tmp_path):
    versions, digests = _now(tmp_path)
    lock = _locked(versions, digests)
    bumped = dict(versions, **{"suite-passed": _next_major(versions)})
    problems = lock_problems(bumped, digests, lock)
    assert len(problems) == 1 and "update the lock file" in problems[0]
    updated = dict(lock, **{"suite-passed": {"version": _next_major(versions),
                                             "verdict_digest": digests["suite-passed"]}})
    assert lock_problems(bumped, digests, updated) == []


def test_ir_6_a_changed_verdict_with_a_major_bump_passes_once_the_lock_is_updated(tmp_path):
    versions, digests = _now(tmp_path)
    lock = _locked(versions, digests)
    bumped = dict(versions, **{"suite-passed": _next_major(versions)})
    changed = dict(digests, **{"suite-passed": "0" * 64})
    assert len(lock_problems(bumped, changed, lock)) == 1
    updated = dict(lock, **{"suite-passed": {"version": _next_major(versions),
                                             "verdict_digest": "0" * 64}})
    assert lock_problems(bumped, changed, updated) == []


def test_ir_6_a_minor_bump_with_the_same_verdicts_needs_no_lock_change(tmp_path):
    versions, digests = _now(tmp_path)
    lock = _locked(versions, digests)
    minor = dict(versions, **{"suite-passed": _next_minor(versions)})
    assert lock_problems(minor, digests, lock) == []


def test_ir_6_a_lower_major_than_the_lock_fails(tmp_path):
    versions, digests = _now(tmp_path)
    lock = _locked(versions, digests)
    lock["suite-passed"]["version"] = _next_major(versions)
    problems = lock_problems(versions, digests, lock)
    assert len(problems) == 1 and "never goes back" in problems[0]


# --- IR-12: the published coverage page ----------------------------------------------------------

def _script():
    spec = importlib.util.spec_from_file_location("impl_coverage", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_ir_12_the_page_lists_each_implementation_with_its_cases_and_what_they_exercise():
    body = _script().render(CORPUS)
    for name, entry in check_registry.REGISTRY.items():
        assert f"### `{name}` (version {entry.version})" in body, name
        for case in sorted(p.name for p in (CORPUS / name).iterdir() if p.is_dir()):
            label = yaml.safe_load((CORPUS / name / case / "expected.yml").read_text())
            assert f"| `{case}` | {label['verdict']} | {label['input']} |" in body, (name, case)


def test_ir_12_the_published_page_is_not_stale():
    page = PAGE.read_text(encoding="utf-8")
    assert MARKER in page, "docs/check-implementations.md has no generated marker"
    assert page.split(MARKER, 1)[1].strip() == _script().render(CORPUS).strip(), (
        "docs/check-implementations.md is stale - regenerate it with "
        "`scripts/impl-coverage.py --write`")


def test_ir_12_a_new_corpus_case_makes_the_page_stale(tmp_path):
    copy = tmp_path / "impls"
    shutil.copytree(CORPUS, copy)
    case = copy / "suite-passed" / "added"
    case.mkdir()
    (case / "expected.yml").write_text("verdict: pass\ninput: a case nobody listed\n")
    assert _script().render(copy).strip() != _script().render(CORPUS).strip()
    assert "a case nobody listed" in _script().render(copy)


def test_ir_12_the_script_prints_what_it_would_write():
    r = subprocess.run([sys.executable, str(SCRIPT)], capture_output=True, text=True,
                       timeout=60, cwd=ROOT)
    assert r.returncode == 0, r.stderr
    assert r.stdout.strip() == _script().render(CORPUS).strip()
