"""Contract 4: the CLI's exit codes on a recorded command corpus at 5.6.0.

Version 6.0.0 rewrites how Compass reads its configuration, over many small
changes. The promise to an existing user is that a project with no
configuration behaves as it did at 5.6.0. Scripts, hooks and CI jobs read
the CLI's exit code to decide whether to stop, so a refusal that becomes a
success, or a success that becomes a refusal, breaks them without a word.

This test runs every entry in the corpus against the project state it names
and compares the exit code with the one 5.6.0 gave. The corpus leans towards
refusals, because a refusal depends on a setting being read at the right
moment, and the rewrite moves those reads. The exit codes were captured once,
before the rewrite began, and are never regenerated by running newer code: a
baseline refreshed from the code under test would agree with any drift.

Scenario id: `TRC-001` (issue `compat-command-corpus`).
"""
from __future__ import annotations

import pytest

import compat_commands as cc

ENTRIES = cc.load()


@pytest.fixture(scope="module")
def projects(tmp_path_factory):
    return cc.Projects(tmp_path_factory.mktemp("contract-4"))


@pytest.mark.parametrize("entry", ENTRIES, ids=[e["id"] for e in ENTRIES])
def test_contract_4_exit_code_matches_the_baseline(projects, entry):
    outcome = projects.run(entry)
    assert cc.differences(entry, outcome) == [], (
        f"{entry['id']}: {cc.differences(entry, outcome)}\n"
        f"stdout:\n{outcome.stdout}\nstderr:\n{outcome.stderr}")


def test_contract_4_the_corpus_is_well_formed():
    ids = [e["id"] for e in ENTRIES]
    assert len(ids) == len(set(ids))
    for entry in ENTRIES:
        assert entry["project"] in cc.STATES, entry["id"]
        assert isinstance(entry["exit"], int), entry["id"]


def test_contract_4_reports_a_refusal_that_no_longer_happens(projects):
    # Proves the contract can fail: the same command in a project whose
    # configuration turns the refusal off must be reported as a difference.
    entry = next(e for e in ENTRIES if e["id"] == "check-quick-fix-enforced")
    assert entry["exit"] != 0
    root = projects.fresh(entry["project"])
    config = root / ".compass" / "config.yml"
    config.write_text(config.read_text(encoding="utf-8").replace(
        "mode: enforced", "mode: advisory"), encoding="utf-8")
    outcome = cc.run_in(root, projects.env, entry["argv"])
    assert outcome.exit == 0, outcome.stdout + outcome.stderr
    assert f"exit 0, recorded {entry['exit']}" in cc.differences(
        entry, outcome)


def test_contract_4_capture_refuses_to_overwrite(tmp_path):
    corpus = tmp_path / "corpus.yml"
    corpus.write_text(cc.CORPUS.read_text(encoding="utf-8"), encoding="utf-8")
    with pytest.raises(RuntimeError, match="already holds captured"):
        cc.capture(corpus)
