"""The issue page draws its traceability chain: GitHub issue #296.

`compass issue dashboard` writes the per-issue page a reviewer opens first.
It now carries a scenario table with red and green marks and a Mermaid
flowchart from intent to scenario to test to evidence, and the existing
staleness check keeps both current.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "cli"))


def _issue(tmp_path: Path, scenarios: int = 3) -> Path:
    task_dir = tmp_path / "work" / "export-data"
    (task_dir / "evidence").mkdir(parents=True)
    scns = [{"id": f"EX-{n}", "title": f"Given case {n}, then it works",
             "intent": "INT-1" if n % 2 else "INT-2", "tests": [f"tests/test_{n}.py"]}
            for n in range(1, scenarios + 1)]
    manifest = {
        "schema_version": "2.0", "task": "export-data", "created": "2026-10-01",
        "status": "active", "delivery_approach": "feature",
        "assessment": {"risk": "contained", "size": "standard"},
        "scenarios": scns, "changed_files": [], "artifacts": [],
        "evidence": [{"id": "EV-T-EX-1", "type": "test-run",
                      "path": "evidence/green-EX-1.json", "scenario": "EX-1"}],
        "gates": [{"id": "verify.correctness", "status": "pass"},
                  {"id": "verify.security", "status": "pending"}],
    }
    (task_dir / "manifest.yml").write_text(yaml.safe_dump(manifest, sort_keys=False))
    for kind, sid in (("red", "EX-1"), ("green", "EX-1"), ("red", "EX-2")):
        (task_dir / "evidence" / f"{kind}-{sid}.json").write_text(json.dumps(
            {"scenario": sid, "timestamp": "2026-10-01T10:00:00+00:00"}))
    return task_dir


def _page(task_dir: Path) -> str:
    from compass_pkg.dashboard import render_dashboard
    return render_dashboard(str(task_dir))


def _row(page: str, sid: str) -> str:
    return next(l for l in page.splitlines() if l.startswith(f"| {sid} |"))


def test_one_row_per_scenario_with_marks(tmp_path):
    """IO-A."""
    page = _page(_issue(tmp_path))
    assert "| Scenario | Title | Red | Green | Acceptance | Evidence |" in page
    one, two, three = _row(page, "EX-1"), _row(page, "EX-2"), _row(page, "EX-3")
    assert one.count("✓") == 2 and "evidence/green-EX-1.json" in one
    assert "✓" in two.split("|")[3] and "○" in two.split("|")[4]
    assert three.count("○") == 3


def test_the_flowchart_draws_the_chain_and_marks_the_open_one(tmp_path):
    """IO-B."""
    page = _page(_issue(tmp_path))
    chart = page.split("```mermaid", 1)[1].split("```", 1)[0]
    assert chart.lstrip().startswith("flowchart")
    for node in ("INT-1", "INT-2", "EX-1", "EX-2", "tests/test_1.py", "green-EX-1.json"):
        assert node in chart, node
    assert "classDef open" in chart
    assert any("EX-2" in line and ":::open" in line for line in chart.splitlines())
    assert not any("EX-1" in line and ":::open" in line for line in chart.splitlines())


def test_many_scenarios_collapse_in_the_chart_only(tmp_path):
    """IO-C."""
    page = _page(_issue(tmp_path, scenarios=30))
    chart = page.split("```mermaid", 1)[1].split("```", 1)[0]
    assert "EX-17" not in chart
    assert "scenarios" in chart
    assert _row(page, "EX-30")


def test_a_later_green_makes_the_page_stale(tmp_path):
    """IO-D."""
    from compass_pkg.dashboard import dashboard_is_current
    task_dir = _issue(tmp_path)
    (task_dir / "README.md").write_text(_page(task_dir))
    assert dashboard_is_current(str(task_dir))[0]
    (task_dir / "evidence" / "green-EX-2.json").write_text(json.dumps(
        {"scenario": "EX-2", "timestamp": "2026-10-01T11:00:00+00:00"}))
    current, detail = dashboard_is_current(str(task_dir))
    assert not current
    assert "compass issue dashboard" in detail


def test_the_status_line_counts_gates(tmp_path):
    """IO-E."""
    page = _page(_issue(tmp_path))
    status = next(l for l in page.splitlines() if l.startswith("**Status:**"))
    assert "gates 1/2" in status


def test_a_page_from_before_this_format_is_not_failed(tmp_path):
    """ADR-006: a README generated by an older Compass lacks the traceability
    section. Upgrading must not turn every such issue red, so the check
    declines on it and says how to regenerate."""
    from compass_pkg import dashboard
    from compass_pkg.check_results import NOTHING_TO_CHECK
    task_dir = _issue(tmp_path)
    old_page = _page(task_dir).replace(dashboard.FORMAT_NOTE + "\n", "")
    old_page = old_page.split("## Traceability", 1)[0]
    (task_dir / "README.md").write_text(old_page)
    import yaml as _y
    result, detail = dashboard._check_dashboard_current(
        _y.safe_load((task_dir / "manifest.yml").read_text()), str(task_dir))
    assert result is NOTHING_TO_CHECK, (result, detail)
    assert "compass issue dashboard" in detail


# --- review round 1 ------------------------------------------------------------

def _chart(page: str) -> str:
    return page.split("```mermaid", 1)[1].split("```", 1)[0]


def _with(tmp_path, mutate):
    task_dir = _issue(tmp_path)
    m = yaml.safe_load((task_dir / "manifest.yml").read_text())
    mutate(m, task_dir)
    (task_dir / "manifest.yml").write_text(yaml.safe_dump(m, sort_keys=False))
    return task_dir


def test_a_shared_test_does_not_lead_an_open_scenario_to_evidence(tmp_path):
    """IO-B: EX-1 is proven, EX-2 is not, and both name the same test."""
    def mutate(m, _):
        for s in m["scenarios"]:
            s["tests"] = ["tests/test_shared.py"]
    chart = _chart(_page(_with(tmp_path, mutate)))
    edges = [l.strip() for l in chart.splitlines() if "-->" in l]
    nodes_of_ex2 = [l.split("-->")[1].split("[")[0].strip() for l in edges
                    if l.split("-->")[0].strip().startswith("s_EX_2")]
    assert nodes_of_ex2, "no edges found from EX-2, so this test checks nothing"
    for node in nodes_of_ex2:
        assert not any(e.startswith(node + " ") and "green" in e for e in edges), edges


def test_ids_and_labels_are_safe_mermaid(tmp_path):
    def mutate(m, _):
        m["scenarios"][0]["id"] = "end"
        m["scenarios"][0]["tests"] = ['tests/test_"quoted"<x>.py']
    chart = _chart(_page(_with(tmp_path, mutate)))
    assert '"quoted"' not in chart and "<x>" not in chart, chart
    assert "#quot;quoted#quot;#lt;x#gt;" in chart, chart
    assert not any(l.strip().startswith("end") for l in chart.splitlines())


def test_an_unproven_scenario_without_a_red_is_open_too(tmp_path):
    chart = _chart(_page(_issue(tmp_path)))
    assert any("EX-3" in l and ":::open" in l for l in chart.splitlines())


def test_an_acceptance_record_shows_in_its_own_column(tmp_path):
    task_dir = _issue(tmp_path)
    (task_dir / "evidence" / "acceptance-EX-3.json").write_text(
        json.dumps({"scenario": "EX-3"}))
    page = _page(task_dir)
    assert "| Scenario | Title | Red | Green | Acceptance | Evidence |" in page
    assert _row(page, "EX-3").split("|")[5].strip() == "✓"


def test_unbound_records_are_named(tmp_path):
    task_dir = _issue(tmp_path)
    (task_dir / "evidence" / "green.json").write_text(json.dumps({"timestamp": "x"}))
    page = _page(task_dir)
    assert "Not tied to a scenario: `evidence/green.json`" in page


def test_both_chart_modes_count_an_accepted_scenario_as_proven(tmp_path):
    """One meaning of proven: a green or an acceptance record."""
    task_dir = _issue(tmp_path, scenarios=30)
    for n in range(1, 31, 2):  # every INT-1 scenario
        (task_dir / "evidence" / f"acceptance-EX-{n}.json").write_text(
            json.dumps({"scenario": f"EX-{n}"}))
    chart = _chart(_page(task_dir))
    assert "15 scenarios, 15 proven" in chart, chart
    small = _issue(tmp_path / "small")
    (small / "evidence" / "acceptance-EX-3.json").write_text(json.dumps({"scenario": "EX-3"}))
    assert not any("EX-3" in l and ":::open" in l for l in _chart(_page(small)).splitlines())
