"""The compatibility contracts: a project with no configuration behaves as
the release the configuration rewrite started from.

Each contract compares today's behaviour with a baseline captured once, at
5.6.0, by `scripts/capture-compat-baseline.py`. A baseline is never
regenerated by running new code: that would record a regression as the
expected result. Every contract also proves it can fail, by changing one
shipped default in memory and expecting a difference.

Contracts 1 and 2 (routing output, and what each delivery approach owes)
live here now; the others join as they are captured.

Scenario id: `TRC-001` (issue `compat-routing-baseline`).
"""
from __future__ import annotations

import copy

import yaml

from compat_baseline import (OWED, compact, grid,
                             load_routing, named_labels, owed_by_approach,
                             routing_differences, shipped_policy)


# --- contract 1: routing output ------------------------------------------------

def test_contract_1_the_baseline_covers_the_whole_grid():
    header, rows = load_routing()
    assert header["version"] == "5.6.0" and header["captured_from"]
    vocabulary = header["vocabulary"]
    expected = [r for r in grid(vocabulary)]
    recorded = [r["assessment"] for r in rows if r["kind"] == "grid"]
    assert recorded == expected, "the baseline does not hold the whole grid"
    assert len(recorded) == 1200
    digests = [r for r in rows if r["kind"] == "label-digests"]
    assert len(digests) == 1200
    assert all(len(r["digests"]) == 2 ** len(header["labels"]) for r in digests)
    assert header["labels"] == ["auth", "migrations", "payments", "personal-data"]
    assert any(r["kind"] == "archive" for r in rows)


def test_contract_1_the_shipped_policy_routes_as_the_baseline():
    header, rows = load_routing()
    differences = routing_differences(shipped_policy(), header, rows)
    assert differences == [], "\n".join(differences[:10])


def test_contract_1_can_fail_when_one_default_changes():
    header, rows = load_routing()
    policy = copy.deepcopy(shipped_policy())
    policy["route_shapes"]["regular"]["gates"] = [
        g for g in policy["route_shapes"]["regular"]["gates"] if g != "verify.regression"]
    assert routing_differences(policy, header, rows, first_only=True), \
        "a dropped gate went unseen"


def test_contract_1_a_change_only_a_label_reaches_is_seen():
    # The label digests are the only record of label subsets; prove they bite.
    header, rows = load_routing()
    policy = copy.deepcopy(shipped_policy())
    for rule in policy["routing_guardrails"]["floors"]:
        if "migrations" in str(rule.get("when")):
            rule["when"] = {"labels_any": ["nothing-matches"]}
    assert named_labels(shipped_policy()) == header["labels"]
    assert routing_differences(policy, header, rows, first_only=True), \
        "a label-only change went unseen"


# --- contract 2: what each delivery approach owes ---------------------------------

def test_contract_2_each_approach_owes_what_it_owed():
    _, rows = load_routing()
    recorded = yaml.safe_load(OWED.read_text(encoding="utf-8"))
    policy = shipped_policy()
    now_rows = [dict(r, result=compact(r["assessment"], policy))
                for r in rows if r["kind"] == "grid"]
    assert owed_by_approach(now_rows) == recorded["owed"]


def test_contract_2_is_a_projection_of_contract_1():
    _, rows = load_routing()
    recorded = yaml.safe_load(OWED.read_text(encoding="utf-8"))
    assert owed_by_approach(rows) == recorded["owed"]


# --- contracts 3 and 6: verdicts and readability over the archive sample ---------

def _archive():
    import json

    from archive import sample_root
    from compat_baseline import ARCHIVE
    return sample_root(), json.loads(ARCHIVE.read_text(encoding="utf-8"))


def test_contract_3_check_gives_the_recorded_verdicts_on_the_archive_sample():
    from compat_baseline import archive_differences, archive_results
    root, recorded = _archive()
    assert recorded["version"] == "5.6.0" and len(recorded["issues"]) == 16
    differences = archive_differences(recorded["issues"], archive_results(root))
    assert differences == [], "\n".join(differences)


def test_contract_6_every_sampled_issue_stays_readable():
    _, recorded = _archive()
    unreadable = {slug: r for slug, r in recorded["issues"].items()
                  if r["lint_exit"] or r["receipt_exit"]}
    assert unreadable == {}


def test_contract_3_can_fail_when_an_issue_loses_its_evidence(tmp_path):
    import shutil

    from compat_baseline import archive_differences, archive_results
    root, recorded = _archive()
    slug = next(s for s, r in recorded["issues"].items()
                if r["verdicts"].get("suite-passed") == "pass")
    copy = tmp_path / "sample"
    shutil.copytree(root, copy)
    shutil.rmtree(copy / ".compass" / "work" / slug / "evidence")
    now = archive_results(copy, only={slug})
    assert archive_differences({slug: recorded["issues"][slug]}, now)
