#!/usr/bin/env python3
# =============================================================================
# compass - the per-issue review dashboard
# =============================================================================
# The page a reviewer opens first. An issue directory answers "what files
# exist"; this answers the questions a reviewer actually has - what am I being
# asked to approve, what should I read, and what was deliberately left out.
#
# IT CARRIES NO RAW EVIDENCE. Command output and test runs are linked, never
# reproduced. A review page that reproduces its evidence stops being two screens
# and stops being read, which is the whole complaint this page answers.
#
# It is generated, never hand-edited, and a check fails when it no longer
# matches the manifest. A generated page nobody checks is still trusted,
# which is worse than no page.
#
# DEPENDENCY: PyYAML, bundled at cli/vendor/yaml/ and pinned in
# THIRD-PARTY-NOTICES.md. cli/compass_pkg/__init__.py resolves it, and it is
# the only third-party code Compass ships; everything else is the Python 3
# standard library. This module reaches it through compass_pkg.core.
# =============================================================================
"""Rendering the per-issue review dashboard from the artifact registry."""
from __future__ import annotations

import os

from compass_pkg import lifecycle, status_words
from compass_pkg.check_results import NOTHING_TO_CHECK
from compass_pkg.core import (FOUND, CompassError, _registered_path, canonical_shape, docs_dir,
                             load_yaml, manifest_path, resolve_artifact,
                             resolve_issue_dir, save_manifest)

# The line that says the page was generated, and the marker the up-to-date
# check reads. Kept out of the rendered body's meaning so a reader is not
# asked to care about it.
GENERATED_NOTE = ("<!-- GENERATED by `compass issue dashboard` - do not edit. "
                  "Regenerate after any stage. -->")

# The page's format. A page without this line was written by a Compass from
# before the traceability section, and the check declines on it rather than
# failing it, so upgrading does not turn every issue red (ADR-006).
FORMAT_NOTE = "<!-- compass issue dashboard format: traceability -->"

_STATUS_ORDER = {"awaiting-approval": 0, "draft": 1, "approved": 2,
                 "superseded": 3, "omitted": 4}


def _spine(task_dir):
    path = manifest_path(task_dir)
    try:
        task = load_yaml(path)
    except CompassError:
        return {}
    if not isinstance(task, dict):
        return {}
    # An approach recorded under an old name shows under its current one.
    if task.get("delivery_approach"):
        task["delivery_approach"] = canonical_shape(task["delivery_approach"])
    return task


def _artifacts(task):
    arts = task.get("artifacts")
    return [a for a in arts if isinstance(a, dict)] if isinstance(arts, list) else []


def _state_text(task, task_dir):
    """The state of the issue as `compass flow` reports it. An in-flight issue
    stores no status, so the state is read from its records; a done issue adds
    its close reason, and a blocked flag is named."""
    if not task:
        return "?"
    state = lifecycle.state_of(task, task_dir)
    reason = status_words.close_reason(task)
    if state == "done" and reason:
        state = "%s (%s)" % (state, reason)
    flag = lifecycle.blocked_flag(task, task_dir)
    if flag:
        state += " (blocked: %s)" % (flag.get("reason") or "no reason recorded")
    return state


def _decision_line(task, pack):
    """What the reviewer is being asked, in one sentence.

    Taken from the artifact that is awaiting approval. When nothing awaits one,
    the page says so rather than inventing a decision - "no decision required"
    is a real answer and a reviewer needs it as much as any other.
    """
    waiting = [a for a in pack if a.get("status") == "awaiting-approval"]
    if not waiting:
        return None, "No decision required. Nothing is awaiting approval."
    first = waiting[0]
    return first, "Approve the %s - %s." % (first.get("kind", "document"),
                                            (first.get("reason") or "").rstrip("."))


# Past this many scenarios the flowchart shows one summary node per intent,
# so it stays readable; the table above it still lists every scenario (#296).
CHART_SCENARIO_LIMIT = 25


def _records(task_dir):
    """({(kind, scenario): file name}, [unbound file names]) for the issue's
    red, green and acceptance records."""
    import glob
    import json
    out, unbound = {}, []
    for path in sorted(glob.glob(os.path.join(task_dir, "evidence", "*.json"))):
        name = os.path.basename(path)
        kind = next((k for k in ("red", "green", "acceptance") if name == f"{k}.json"
                     or name.startswith(f"{k}-")), None)
        if kind is None or name == "acceptance-baseline.json":
            continue
        try:
            with open(path, encoding="utf-8") as fh:
                data = json.load(fh)
        except (OSError, ValueError):
            data = {}
        scenario = (data.get("scenario") if isinstance(data, dict) else None) \
            or name[len(kind) + 1:-5]
        if scenario:
            out.setdefault((kind, str(scenario)), name)
        else:
            unbound.append(name)
    return out, unbound


def _node(kind, *parts):
    """A Mermaid node id, prefixed by its kind so no id is a keyword such as
    `end` and an intent never collides with a scenario."""
    import re
    return kind + "_" + "_".join(re.sub(r"\W", "_", str(p)) for p in parts)


def _label(text):
    """A node label with the characters Mermaid would misread encoded."""
    return (str(text).replace("&", "#amp;").replace('"', "#quot;")
            .replace("<", "#lt;").replace(">", "#gt;"))


def _traceability(task, task_dir):
    """The scenario table and the flowchart, as markdown lines."""
    scenarios = [s for s in task.get("scenarios") or [] if isinstance(s, dict)]
    out = ["## Traceability", ""]
    if not scenarios:
        return out + ["No scenarios recorded yet.", ""]
    records, unbound = _records(task_dir)
    out += ["| Scenario | Title | Red | Green | Acceptance | Evidence |",
            "|---|---|---|---|---|---|"]
    for s in scenarios:
        sid = str(s.get("id", "?"))
        green = records.get(("green", sid))
        title = str(s.get("title", "")).replace("|", "-")
        out.append("| %s | %s | %s | %s | %s | %s |" % (
            sid, title, "✓" if ("red", sid) in records else "○",
            "✓" if green else "○",
            "✓" if ("acceptance", sid) in records else "○",
            "`evidence/%s`" % green if green else "-"))
    if unbound:
        out += ["", "Not tied to a scenario: " + ", ".join(
            "`evidence/%s`" % n for n in unbound)]
    out += ["", "```mermaid", "flowchart LR",
            "  classDef open stroke-dasharray: 4 4"]
    by_intent = {}
    for s in scenarios:
        intents = s.get("intent") or "no intent"
        for intent in intents if isinstance(intents, list) else [intents]:
            by_intent.setdefault(str(intent), []).append(s)
    seen = set()

    def edge(line):
        if line not in seen:
            seen.add(line)
            out.append(line)

    if len(scenarios) > CHART_SCENARIO_LIMIT:
        for intent, group in by_intent.items():
            proven = sum(1 for s in group if ("green", str(s.get("id"))) in records
                         or ("acceptance", str(s.get("id"))) in records)
            edge('  %s["%s"] --> %s["%d scenarios, %d proven"]' % (
                _node("i", intent), _label(intent), _node("all", intent),
                len(group), proven))
    else:
        for intent, group in by_intent.items():
            for s in group:
                sid = str(s.get("id", "?"))
                green = records.get(("green", sid))
                proven = bool(green) or ("acceptance", sid) in records
                edge('  %s["%s"] --> %s["%s"]%s' % (
                    _node("i", intent), _label(intent), _node("s", sid), _label(sid),
                    "" if proven else ":::open"))
                # A test node belongs to its scenario, so a test two
                # scenarios share cannot lead an open one to the other's
                # evidence.
                for test in s.get("tests") or []:
                    tnode = _node("t", sid, test)
                    edge('  %s --> %s["%s"]' % (_node("s", sid), tnode, _label(test)))
                    if green:
                        edge('  %s --> %s["%s"]' % (tnode, _node("e", sid, green),
                                                    _label(green)))
    out += ["```", ""]
    return out


def render_dashboard(task_dir):
    """The review page for one issue, as markdown."""
    task = _spine(task_dir)
    slug = task.get("task") or os.path.basename(os.path.abspath(task_dir))
    assessment = task.get("assessment") or {}
    pack = sorted(_artifacts(task),
                  key=lambda a: _STATUS_ORDER.get(a.get("status"), 9))
    present = [a for a in pack if a.get("status") != "omitted"]
    omitted = [a for a in pack if a.get("status") == "omitted"]
    waiting, decision = _decision_line(task, pack)

    out = [GENERATED_NOTE, FORMAT_NOTE, "", "# %s" % slug, ""]

    approach = task.get("delivery_approach") or "not yet routed"
    bits = [str(approach)]
    if assessment.get("risk"):
        bits.append("%s risk" % assessment["risk"])
    if assessment.get("size"):
        bits.append("%s" % assessment["size"])
    gates = [g for g in task.get("gates") or [] if isinstance(g, dict)]
    passed = sum(1 for g in gates if g.get("status") == "pass")
    out += ["**Status:** %s · **Approach:** %s · gates %d/%d" % (
        _state_text(task, task_dir), " · ".join(bits), passed, len(gates)), ""]

    out += ["## Decision required", "", decision, ""]
    if waiting is not None and waiting.get("path"):
        out += ["**Read:** `%s`" % waiting["path"], ""]

    # The status column asks the resolver, not just the registry. Routing seeds
    # every earned document as `draft` and nothing moves it, so the registry
    # alone cannot say whether a document exists. A page that sends a reviewer
    # looking for a file that is not there is worse than no page - it is
    # confidently wrong.
    out += ["## Review pack", ""]
    if present:
        out += ["| Document | Status | Why it exists |", "|---|---|---|"]
        for a in present:
            kind = a.get("kind", "?")
            state, _p, _why = resolve_artifact(task_dir, kind)
            # A registry status on a file that is not there means nothing, so
            # the disk wins. The resolver cannot tell "the entry names the
            # wrong path" from "nobody has written it yet" - on disk they are
            # the same absence - so both get the label that is true either way.
            status = a.get("status", "?") if state == FOUND else "not written yet"
            out.append("| %s | %s | %s |" % (
                kind, status, (a.get("reason") or "").replace("|", "-")))
    else:
        out.append("No documents registered yet.")
    out.append("")

    out += ["## Deliberately omitted", ""]
    if omitted:
        for a in omitted:
            out.append("- **%s** - %s" % (a.get("kind", "?"),
                                          (a.get("reason") or "no reason recorded")))
    else:
        out.append("Nothing recorded as omitted.")
    out.append("")

    out += _traceability(task, task_dir)

    # Evidence is LINKED. The registry entries are named and their paths given;
    # nothing is read out of the record files themselves.
    registry = [e for e in (task.get("evidence") or []) if isinstance(e, dict)]
    out += ["## Evidence", ""]
    if registry:
        out.append("Linked, not reproduced - open a record to read it.")
        out.append("")
        for e in registry:
            out.append("- `%s` (%s) - `%s`" % (e.get("id", "?"), e.get("type", "?"),
                                               e.get("path", "no path")))
    else:
        out.append("No evidence recorded yet.")
    out.append("")
    return "\n".join(out) + "\n"


def dashboard_is_current(task_dir):
    """Does the dashboard on disk match one rendered from the manifest now?

    Returns (is_current, detail). A page that no longer matches its source is
    worse than no page, because it is still trusted.
    """
    path = os.path.join(task_dir, "README.md")
    if not os.path.isfile(path):
        return False, ("no README.md - regenerate it with "
                       "`compass issue dashboard render`")
    with open(path, encoding="utf-8") as fh:
        on_disk = fh.read()
    if GENERATED_NOTE not in on_disk:
        # Someone hand-wrote it. Say so rather than overwriting silently.
        return False, ("README.md was not generated by Compass - it carries no "
                       "generated marker. Regenerate it with `compass issue "
                       "dashboard render`, or move the hand-written page aside first")
    fresh = render_dashboard(task_dir)
    if on_disk.strip() != fresh.strip():
        return False, ("README.md no longer matches the manifest - "
                       "regenerate it with `compass issue dashboard render`")
    return True, "README.md matches the manifest"


def stale_page_reminder(task_dir):
    """The one line a verb that writes the manifest prints when it has left
    the review page behind, or None.

    Silent when there is no page, or a page someone wrote by hand: neither was
    generated from the manifest, so neither went stale because of it. The
    page is never regenerated here - the dashboard-current check keeps its
    reach only while a person runs `compass issue dashboard render` themselves.
    """
    path = os.path.join(task_dir, "README.md")
    if not os.path.isfile(path):
        return None
    with open(path, encoding="utf-8") as fh:
        if GENERATED_NOTE not in fh.read():
            return None
    current, _ = dashboard_is_current(task_dir)
    if current:
        return None
    return ("the review page no longer matches the manifest - run "
            "`compass issue dashboard render` to regenerate it")


def _check_dashboard_current(task, task_dir):
    """The per-issue review page still matches the record it was generated from.

    Evidence, not assertion (`G4`): the dashboard states what documents exist,
    what is awaiting approval and what was left out. If the manifest has moved
    since it was rendered, that page is an assertion the record contradicts -
    and it is the page a reviewer approves from, so nobody catches it.

    Two outcomes DECLINE rather than pass, and the distinction is the point.
    An issue with no dashboard is not being misled by one, and neither is a
    reader of a page a person wrote by hand. Reporting either as a pass would
    make this a check that clears without reading anything.
    """
    path = os.path.join(task_dir, "README.md")
    if not os.path.isfile(path):
        return NOTHING_TO_CHECK, ("no README.md on this issue - there is no "
                                  "generated review page to be out of date")
    with open(path, encoding="utf-8") as fh:
        on_disk = fh.read()
    if GENERATED_NOTE not in on_disk:
        return NOTHING_TO_CHECK, (
            "README.md carries no generated marker, so it is a page "
            "somebody wrote by hand - Compass does not judge it against "
            "the manifest")
    if FORMAT_NOTE not in on_disk:
        return NOTHING_TO_CHECK, (
            "README.md was generated by an earlier Compass, before the page "
            "drew the traceability chain - run `compass issue dashboard render` to "
            "regenerate it in the current format")

    current, detail = dashboard_is_current(task_dir)
    if not current:
        return False, (detail + " - run `compass issue dashboard render` and re-read "
                       "it before approving anything from it")
    return True, detail

def cmd_issue_dashboard(args):
    """`compass issue dashboard render` - render the review page, or check it is current.

    `--check` writes nothing and reports whether the page still matches the
    manifest. That is the mode an up-to-date guard calls: a generated page
    that no longer matches its source is worse than no page, because it is
    still trusted.
    """
    from compass_pkg.core import resolve_issue_dir

    task_dir = resolve_issue_dir(getattr(args, "task", None))
    if getattr(args, "check", False):
        current, detail = dashboard_is_current(task_dir)
        print("compass issue dashboard render: %s - %s"
              % ("current" if current else "STALE", detail))
        return 0 if current else 1

    page = render_dashboard(task_dir)
    path = os.path.join(task_dir, "README.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(page)
    from compass_pkg.terminal import say

    return say(args, "compass issue dashboard render: written -> %s" % path,
               detail=["%d line(s). Evidence is linked, not reproduced."
                       % len(page.splitlines())],
               path=path, lines=len(page.splitlines()))


# The statuses a document can be in. `draft` is what routing seeds; the rest
# are decisions a person records with `compass issue artifact set`.
ARTIFACT_STATUSES = ("draft", "awaiting-approval", "approved", "superseded",
                     "omitted")


def cmd_issue_artifact_path(args):
    """`compass issue artifact-path <kind>` - where a document is, one answer.

    Exists for the two hooks. They are shell and cannot import the resolver.
    A second resolver in bash would come to disagree with the Python one
    about where a document lives.

    Exits non-zero and prints nothing when it is not there. A bash caller
    reads the exit code first; a plausible path for a missing document would
    let a hook conclude that assessment ran when it did not.
    """
    task_dir = resolve_issue_dir(getattr(args, "task", None))
    kind = args.kind[:-3] if args.kind.endswith(".md") else args.kind
    state, path, reason = resolve_artifact(task_dir, kind)
    if state != FOUND:
        raise CompassError(
            "%s: %s (%s)" % (kind, state, reason))
    print(path)
    return 0


def _record_freshness(task, task_dir, path, entry):
    """With the capability `artifact-freshness` on, stamp the entry with the
    digests of its file and its upstream, and save. The lines to show; none
    when the capability is off, so the verb is the same as before."""
    from compass_pkg import effective, freshness

    try:
        view = effective.view_or_legacy(task_dir)
    except Exception:  # noqa: BLE001 - an unreadable configuration records nothing
        return []
    if not freshness.stamp(view, task, task_dir, entry):
        return []
    save_manifest(task, path)
    upstream = sorted(entry.get("upstream") or {})
    return ["freshness: digest recorded"
            + (" against %s" % ", ".join(upstream) if upstream else "")]


def _refuse_unreadable(task, task_dir, kind):
    """With the capability `artifact-freshness` on, refuse to register a
    document that, or an upstream that, exists and cannot be read. Nothing is
    saved: a status stored with no digest would leave the document untracked."""
    from compass_pkg import effective, freshness

    try:
        view = effective.view_or_legacy(task_dir)
    except Exception:  # noqa: BLE001 - an unreadable configuration records nothing
        return
    found = freshness.unreadable(view, task, task_dir, kind)
    if found:
        raise CompassError(
            "%s cannot be read, so its digest cannot be recorded. Make the file "
            "readable and register the document again." % ", ".join(found))


def cmd_issue_artifact(args):
    """`compass issue artifact set <kind> --status <s> [--reason ...]`.

    Refuses a kind the issue never earned, the way `tdd-red --scenario`
    refuses a scenario id that is not in the manifest - a status set on a document
    nobody asked for is a typo that would otherwise be stored as a decision.

    An omission MUST carry a reason. Without one, a document deliberately
    dropped and a document nobody got to look the same on the page, and telling
    those apart is the reason the registry exists.
    """
    task_dir = resolve_issue_dir(getattr(args, "task", None))
    path = manifest_path(task_dir)
    task = load_yaml(path)
    arts = [a for a in (task.get("artifacts") or []) if isinstance(a, dict)]

    entry = next((a for a in arts if a.get("kind") == args.kind), None)
    if entry is None:
        earned = ", ".join(sorted(a.get("kind", "?") for a in arts)) or "none"
        raise CompassError(
            "%r is not a document this issue earned (it earned: %s). The "
            "artifact set is computed from the assessment - re-run "
            "`compass approach evaluate --write`, or re-assess with "
            "`/compass:assess --reassess` if the work really changed shape."
            % (args.kind, earned))

    if args.status == "omitted" and not (args.reason or "").strip():
        raise CompassError(
            "omitting %r needs --reason. An omission with no reason is "
            "indistinguishable from a document nobody got to, and telling "
            "those apart is the whole point of recording it." % args.kind)

    rel = (getattr(args, "path", None) or "").strip()
    if rel:
        # Refused here rather than only at read time. The registry is an
        # ordinary file in the repository, so a path in it is data someone can
        # write; catching an escape when the entry is READ means the bad entry
        # is already recorded and the refusal arrives later, somewhere else.
        resolved, refused = _registered_path(task_dir, rel)
        if refused:
            raise CompassError(
                "%r resolves outside the project (%s). A registry path is "
                "measured from the project root, and an issue's document "
                "lives inside the repository - write it under %s and register "
                "that." % (rel, resolved, docs_dir(task_dir)))
        entry["path"] = rel.replace(os.sep, "/")

    if args.status != "omitted":
        _refuse_unreadable(task, task_dir, args.kind)
    entry["status"] = args.status
    if (args.reason or "").strip():
        entry["reason"] = args.reason.strip()
    task["artifacts"] = arts
    save_manifest(task, path)
    recorded = _record_freshness(task, task_dir, path, entry)
    from compass_pkg.terminal import say

    return say(args, "compass issue artifact set: %s -> %s" % (args.kind, args.status),
               detail=["reason: %s" % entry.get("reason", "(none recorded)")]
               + recorded
               + [line for line in [stale_page_reminder(task_dir)] if line],
               kind=args.kind, status=args.status,
               reason=entry.get("reason"))
