#!/usr/bin/env python3
# =============================================================================
# impl-coverage - what each check implementation's fixture corpus exercises
# =============================================================================
# ADR-038 asks for a derived page that lists, per implementation, its corpus
# cases and what each exercises. The page is a view of two things: the
# registry (the version of each implementation) and the corpus (each case's
# `expected.yml`, which holds a verdict and a line saying what the input is).
# Nothing on the page is written by hand.
#
# DEPENDENCY: standard library (argparse, sys, pathlib), and compass_pkg
# (the registry, and its YAML reader, which is the bundled PyYAML).
# =============================================================================
"""Print, or write, the generated part of docs/check-implementations.md.

    scripts/impl-coverage.py            print the generated part
    scripts/impl-coverage.py --write    replace it in docs/check-implementations.md
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "cli"))

from compass_pkg.check_registry import REGISTRY  # noqa: E402
from compass_pkg.core import load_yaml  # noqa: E402

PAGE = ROOT / "docs" / "check-implementations.md"
CORPUS = ROOT / "tests" / "fixtures" / "impls"
MARKER = "<!-- generated by `scripts/impl-coverage.py` -->"


def render(corpus: Path = CORPUS) -> str:
    """The generated part of the page: one section per implementation, with a
    row per corpus case."""
    out = []
    for name, entry in sorted(REGISTRY.items()):
        # A check's identifier can hold a retired word. The identifier is not
        # prose, so that one line says so, as the prose scans ask.
        mark = ("  <!-- vocabulary-scan: allow - the check's identifier, not prose -->"
                if "backfill" in name else "")
        out += [f"### `{name}` (version {entry.version}){mark}", "",
                "| Case | Verdict | What the input exercises |", "|---|---|---|"]
        for case in sorted(p for p in (corpus / name).iterdir() if p.is_dir()):
            label = load_yaml(str(case / "expected.yml"))
            out.append(f"| `{case.name}` | {label['verdict']} | {label['input']} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--write", action="store_true",
                        help="replace the generated part of docs/check-implementations.md")
    args = parser.parse_args(argv)
    body = render()
    if not args.write:
        print(body, end="")
        return 0
    page = PAGE.read_text(encoding="utf-8")
    if MARKER not in page:
        print(f"{PAGE} has no generated marker: {MARKER}", file=sys.stderr)
        return 2
    PAGE.write_text(page.split(MARKER, 1)[0] + MARKER + "\n\n" + body, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
